### ISSUE TITLE
Add test dataset to test diff. meth. reports 

### ISSUE THREAD

**Issue by katwre** [BIMSBbioinfo/pigx_bsseq#103]
Right now with default parameters from the setting file (https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/tests/settings.yaml), there are no diff. meth. cytosines found and it's not possible to test differential methylation reports.

**Comment by Blosberg** [comment]
I've applied the pipeline to the use-case data set ( https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE48519 ). --the "day 3" data set is relatively small, and could potentially be packaged with the repo; for the moment, however, we know that we can run the tests on these data sets on our own.

**Comment by alexg9010** [comment]
seems to be fixed in https://github.com/BIMSBbioinfo/pigx_bsseq/pull/159
