### ISSUE TITLE
print meaningful error when sample sheet has an extra line

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#104]
currently, if the sample sheet is prepared like this (notice the trailing newline):
```
SRX317877_WT.fq.gz,,WT,WGBS,0
SRX317883_tet2.fq.gz,,tet2,WGBS,1
SRR1578163_WT-day3.fastq.gz,,WTday3,WGBS,2
SRR1578165_tet2-day3.fastq.gz,,tet2day3,WGBS,3

```

The output will look like this:

```
$ ./pigx-bsseq samplesheet_usecase.csv -s  settings_usecase.yaml -n
Traceback (most recent call last):
  File "./pigx-bsseq", line 400, in <module>
    args.settings)
  File "./pigx-bsseq", line 241, in generate_config
    sample_params = parse_samples(lines)
  File "./pigx-bsseq", line 163, in parse_samples
    sample_ids = [x[2] for x in rows]
  File "./pigx-bsseq", line 163, in <listcomp>
    sample_ids = [x[2] for x in rows]
IndexError: list index out of range
```
which is not a clear way of saying "you've got an empty line at the end of your sample sheet". I just wasted about 20 minutes trying to figure out what the problem is --a novice user could easily make the same mistake and just give up on the whole package. 

There needs to be a clear message in this case saying "remove the empty line in your sample sheet" (preferably based on checking the length of each line entry in the whole sample sheet).

**Comment by alexg9010** [comment]
I had a similar issue in the chipseq pipeline, 
can you replace the line here https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/pigx-bsseq.in#L156 with this and see wether this solves the issue?
 
```
rows = rows[1:]
rows = [row for row in rows if row[0]]
```

**Comment by rekado** [comment]
Yeah, we should simply strip empty lines instead of bailing out.

**Comment by Blosberg** [comment]
The specific case of when a line is empty is now handled, so this is being downgraded from a "bug" to a "wishlist" item.
https://github.com/BIMSBbioinfo/pigx_bsseq/issues/105
