### ISSUE TITLE
make distcheck error with older version. 

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#113]
![screen shot 2018-03-01 at 15 01 49](https://user-images.githubusercontent.com/23317778/36896977-0dcbe088-1e15-11e8-83ef-e221bfcf87d7.png)

This is the output that I was getting when I was using Autoconf version: 2.63

Then I updated autoconf to the guix version 2.69, and then everything worked wonderfully.

**Comment by katwre** [comment]
@Blosberg so can we close this issue?

**Comment by Blosberg** [comment]
ricardo is looking into it now because he wants to make everything compatible with older versions of autoconf --that's why he asked me to post this issue. Ricardo can close it.

**Comment by Blosberg** [comment]
@rekado , as long as we're using up-to-date autoconf, the user won't even know this is a problem. Can I `wishlist` this?

**Comment by Blosberg** [comment]
Solution: upgrade Autotools to version 2.69, and then this issue is solved.
