### ISSUE TITLE
strange histogram of CpG coverage --problem with deduplication?

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#114]
One of the first plots has this weird region of empty space on the right. We should adjust the xlim values or just leave this plot out.

![weird_empty_plot_region](https://user-images.githubusercontent.com/23317778/36917272-b39b2028-1e56-11e8-9377-dc89b3cdfc4e.png)

**Comment by Blosberg** [comment]
@alexg9010 , can you take a look at this please? the problem is from line 174 in index.Rmd.in, here:
https://github.com/BIMSBbioinfo/pigx_bsseq/blob/3e89fb358bca8ae306f1ca4f3305a325e4a3958b/report_templates/index.Rmd.in#L174

Either it's a problem with Methylkit, or we need to explicitly define the breaks as an input in the R-markdown, but right now, this looks really weird in the final report.

**Comment by alexg9010** [comment]
There is no general problem in methylKit, getCoverageStats() simply calls hist() on the coverage. 
From what I see there are a few bases (~0.2% of all ) that are covered by around 10^7 reads, which is the reason why the x-axis extends to the right. 

We could solve this by using the functionality of getCoverageStats() to accept arguments for hist() [see here](https://github.com/al2na/methylKit/blob/master/R/backbone.R#L1516-L1526), so we could restrict xlim (which would only solve this particular case ) or reduce the number of bins (which decreases the resolution of the histogram).

**Comment by Blosberg** [comment]
ok, it seems the histogram is correct, and there really are just a small fraction of reads with far higher coverage --but this suggests that deduplication is not working as it should be. I'm looking into that now.

**Comment by Blosberg** [comment]
Indeed, it seems we are not deduplicating, because we need to sort first, and _then_ deduplicate. I'm writing a patch for that now.

**Comment by Blosberg** [comment]
Deduplication is now restored using samtools v 1.7, and a restructuring of the BSseq pipeline in this merger: https://github.com/BIMSBbioinfo/pigx_bsseq/pull/124
