### ISSUE TITLE
fix deduplication for pair-end samples

### ISSUE THREAD

**Issue by katwre** [BIMSBbioinfo/pigx_bsseq#116]
currently we use `samtools fixmate`, but it doesn't do deduplication, it only marks bam files - it cleans up read pairing information and flags. Even if we use `samtools fixmate` then we should at least first sort bam files by name according to the documentation http://www.htslib.org/doc/samtools.html to use `samtools fixmate` properly.

**Comment by alexg9010** [comment]
You might have a look at new markdup from samtools, they have a short example. 
Also we were using rmdup before, which is depricated now, so we should change this.

**Comment by Blosberg** [comment]
`markdup ` does this as long as the `-r` option is set for "removal" of the deuplicates. This issue is resolved in this merger: https://github.com/BIMSBbioinfo/pigx_bsseq/pull/124
