### ISSUE TITLE
consolidate tables in diff_meth chromosome table

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#126]
In the diff meth report, we print 3 (rather large tables) tabulating the number of entries per chromosome for differential, hypo-, and hyper- methylated CpGs. The tables are large and take up a lot of space and should be consolidated to a single table with _columns_ for hyper- and hypo- methylation (and maybe one more for 'total').

That amounts to rewriting the function here: 
https://github.com/BIMSBbioinfo/pigx_bsseq/blob/e82df9b582ef208bd487dfe874535d1f6dc96a52/report_templates/diffmeth.Rmd.in#L250

but first we have to check that all seqlabels are accounted for : in case one of the chromosomes has some hypermethylated CpGs but no hypomethylated CpGs, the `seqlevels` will be different, and they have to be tabulated consistently. I don't have time to do this now.

**Comment by alexg9010** [comment]
I removed tables for single base pair resolution results and replaced them with figures. 
If the user is interested in detailed results per base, they can continue to work with the tabix files and/or the result tables we created.

**Comment by alexg9010** [comment]
fixed in https://github.com/BIMSBbioinfo/pigx_bsseq/pull/159
