### ISSUE TITLE
validate settings file and sample sheet

### ISSUE THREAD

**Issue by katwre** [BIMSBbioinfo/pigx_bsseq#14]
e.g. if we dont check that there is the cluster_run arg in the tablesheet then we get an error:

[kwreczy@beast:~/repositories/pigx_bsseq] (1119) $ ./PIGx_BS.sh -t ./test_dataset/TableSheet_test.txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'cluster_run'

another thing is to check that treatment values for differential methylation are numeric

**Comment by rekado** [comment]
Since we provide defaults, there cannot be any missing settings keys, so the original bug report is fixed.

We should still try to validate other inputs, however, e.g. that files mentioned in the sample sheet do in fact exist.

**Comment by Blosberg** [comment]
Fixed with this:
https://github.com/BIMSBbioinfo/pigx_bsseq/pull/72

We now check that all paths (except output-dir) exist, and that there is exactly one `.fasta` or `.fa` file in the genome directory. either zero (missing) or more than one (ambiguous) raises an error.
