### ISSUE TITLE
Comments needed in pigx-bsseq.in

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#140]
Particularly around the qsub section of pigx-bsseq.in (i.e. from around line 500 to the end), it becomes really hard to read an quickly understand what is going. e.g. where exactly is the qsub command being executed? where is it being combined with the variable `command`? what is `format()` doing? etc.

A few comments around here would be very helpful for readability.

**Comment by rekado** [comment]
It's building up a command string (stored in `command`), before finally executing it with either `subprocess.Popen` or `subprocess.run`.

`format` is the Pythonic approach to building up strings out of variables.  (This is superior to plain string concatenation.)

**Comment by Blosberg** [comment]
ok, so if I understand, qsub is first defined here https://github.com/BIMSBbioinfo/pigx_bsseq/blob/f7508cb0b5350b79652d310f5b15cb03f6cdd09c/pigx-bsseq.in#L504

and then incorporated into the larger string "command" here: https://github.com/BIMSBbioinfo/pigx_bsseq/blob/f7508cb0b5350b79652d310f5b15cb03f6cdd09c/pigx-bsseq.in#L509
, but I'm surprised that the `qsub` string isn't at the beginning of all that. 

Could you add some clarifying comment on this to the branch that I've created below? (this should move the snakemake log files to their own directory, but I haven't tested it yet. Once everything passes tests, then I'll open a PR)

https://github.com/BIMSBbioinfo/pigx_bsseq/compare/store_SM_logfiles?expand=1
