### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by xie186** [BIMSBbioinfo/pigx_bsseq#143]
Hi, I was try to use the docker image here:https://hub.docker.com/r/bimsbbioinfo/pigx_bsseq
It seems that this is pretty old with a `test` tag. I'm wondering whether the image file can be released and then we can use it. Thanks.

**Comment by rekado** [comment]
Hi,

I recommend to use Guix to install the latest version of PiGx.  The Docker image is really just a demonstration.  You can also use Guix to build the Docker image.

~~ Ricardo

**Comment by xie186** [comment]
Thanks Ricardo. Can you give some details about "use Guix to build the Docker image.". Thanks.

**Comment by rekado** [comment]
In [our paper](https://doi.org/10.1093/gigascience/giy123) we talk about why we think that application bundles aren't a great fit for reproducible science, and we propose to use [GNU Guix](https://guix.gnu.org) instead.  The Guix project addresses reproducibility issues at the package level and aims to provide bit-for-bit reproducible packages that offer a transparent path from source code to binary.

The Docker image on hub.docker.com has also been generated from a Guix package definition.  We explain a little how we got there at https://hub.docker.com/r/bimsbbioinfo/pigx, which is the (stale) Docker application bundle for the whole pipeline collection. 

You don't actually have to use Docker at all, though, and could use Guix directly.  Once you have Guix installed you can run `guix install pigx` and you're good to go.

**Comment by xie186** [comment]
Thank you @rekado. I successfully installed it using `guix`. The installation of `guix` spent me quite some time. Once it is installed, it's very easy to install `pigx` tools. I'll share my notes about installation of `guix` here later in case there is anyone interested in.
