### ISSUE TITLE
pigx_bsseq for RRBS

### ISSUE THREAD

**Issue by xie186** [BIMSBbioinfo/pigx_bsseq#145]
Hi, thanks for develop pigx_bsseq. I'm wondering whether it is possible to allow us to enable `--rrbs`  (https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md#rrbs-specific-options-mspi-digested-material) so that pigx can process MspI digested RRBS data. Thanks in advance. 

For example, in the `general` section, if we add

```
......
    RRBS: --rrbs  ## OR empty
```
then in the snakemake file, we can add `config["general"]["RRBS"]` in `trim_galore` command line.

**Comment by alexg9010** [comment]
Hi @Xie186, 


Sorry for the very late reply. 

If you want to pass arguments to trim galore you may do so in the tools section of the settings file, where each tool we use has an 'args' parameter that is forwarded to the tool call. 

Hope this helps, 
Best Alex
