### ISSUE TITLE
update guix.scm

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#165]
I guess I missed to update the guix.scm as I added some more dependencies recently. 

Most recent manifest would be this: https://github.com/BIMSBbioinfo/pigx_bsseq/blob/master/dev/guix/manifest.scm

**Comment by alexg9010** [comment]
@rekado maybe you could also simplify the guix.scm as you did for the other pipelines?

**Comment by rekado** [comment]
Alexander Blume (Gosdschan) <notifications@github.com> writes:

> @rekado maybe you could also simplify the guix.scm as you did for the other pipelines?

Certainly.  One thing to note is that this will make “guix.scm” depend
on the currently installed version of Guix.  Ideally, we’ll make sure
it’ll always work with the latest version of Guix.

-- 
Ricardo
