### ISSUE TITLE
Missing pigx-common file in source installation

### ISSUE THREAD

**Issue by AnjaCaRa** [BIMSBbioinfo/pigx_bsseq#183]
When running ./bootstrap.sh in the course of pigx_bsseq source installation the following error occurs:

`./bootstrap.sh
    ./bootstrap.sh
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I pigx-common/common/m4
aclocal: warning: couldn't open directory 'pigx-common/common/m4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /gnu/store/c0fl0g4kn9s6kb142l6dj18sqm53ya4j-autoconf-2.71/bin/autoconf --force
configure.ac:32: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /gnu/store/c0fl0g4kn9s6kb142l6dj18sqm53ya4j-autoconf-2.71/bin/autoconf failed with exit status: 1`

The missing file can be fetch from a set of scripts common to all pigx-pipelines by using 
`git submodule update --init`

**Comment by rekado** [comment]
Yes, you need to fetch all code, including the common submodule.
