### ISSUE TITLE
Not using script directive  

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#22]
Now, using the snakemake script directive creates modified versions of our scripts in the installation folder. We should rather not make use of this and switch to using shell directive calling Rscript on scripts with argument parsers.

**Comment by rekado** [comment]
The only challenge here is to deal with `snakemake@params`.  We would need to find a different way to pass the params field as structured data to the R scripts

**Comment by rekado** [comment]
Commits d43f23eb745860b53987f57c5deab0bb5ba5f210 and 50a637ddd3df0413c1f13c64f6b0d888c59301e9 fix some of these cases.  With your scriptToShell branch we're almost there.

**Comment by rekado** [comment]
Okay, almost done.  Now that we have no more script invocations we can drop the copying of the scripts directory at runtime.
