### ISSUE TITLE
Depricated Command line arguments

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#28]
Since the programs.json is created on configure time we don't need this anymore, right?

**Comment by alexg9010** [comment]
And with the config argument, it only specifies the name of a file that is anyways created on runtime. The user is actually not supposed to modify this file, so he does not need to know about it, right?

**Comment by alexg9010** [comment]
I made up my mind about the progs argument. Since some people might already have their tools installed in some place out of PATH, they should be able to set them manually.

**Comment by katwre** [comment]
:+1:

**Comment by rekado** [comment]
By default the pipeline uses `etc/programs.json`, which is generated at configure time.  At runtime a user may provide an alternative programs.json with `-p`; this gives the user a way to try out different tool versions.  I wouldn't recommend to do things like that, but it is a useful feature; it may be faster to try out a different programs.json than to reconfigure and install the pipeline.

**Comment by rekado** [comment]
Closing this, because we no longer have a separate programs.json.  It's all controlled through the settings.yaml now.
