### ISSUE TITLE
make segmentation and differential methylation optional

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#34]
we just need to comment their output from the input to final_report

**Comment by Blosberg** [comment]
I'm in the middle of branch that solves both this issue and issue #70 , but I'm putting this on hold for Alex's resolution to issue #60 , to make merging easier.

**Comment by Blosberg** [comment]
Solved in this branch: https://github.com/BIMSBbioinfo/pigx_bsseq/pull/78
