### ISSUE TITLE
add version and NEWS

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/pigx_bsseq#36]
similar to Bioc packages, current version and NEWS file that tracks the changes in the pipeline should be incorporated. Feel free to merge this with other issues if this is already open elsewhere.

**Comment by rekado** [comment]
I agree that this is a good thing to have.  It would be much less work to accomplish this if we had good, descriptive commit messages; this would make the review of all changes since the last tagged release only boring rather than maddening :)

**Comment by rekado** [comment]
the current version is stored in VERSION (and this is used by configure.ac and guix.scm for releases); we also have a NEWS file now.
