### ISSUE TITLE
BigWig output is missing

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#37]

**Comment by Blosberg** [comment]
Working on this.

currently, my steps are:
`
> m1 = readRDS(file = "out/07_methyl_calls/{prefix...}.RDS")  # import methylRaw object
> G1 = as(m1 , "GRanges") # convert it to GRanges

> G1$score = G1$numCs/G1$coverage
> G1$coverage = NULL
> G1$numCs    = NULL
> G1$numTs    = NULL  # reduce it to a single metadata column

> export.bw( object = G1, con="/home/bosberg/temp/test.bw")
Error in .local(object, con, format, ...) : 
  Unable to determine seqlengths; either specify 'seqlengths' or specify a genome on 'object' that is known to BSgenome or UCSC
`

Which isn't a very helpful error message. I tried importing the chromosome lengths from the sizes file:

`
> temp = read.csv("/home/bosberg/projects/pigx_bsseq_testing/hg19_std_chrom_sizes_ucsc_sorted.csv", header = FALSE, sep = "\t")

> Sinfo <- Seqinfo(seqnames   = as.character(temp[,1]),
                 seqlengths = temp[,2],
                 genome     ="hg19")
`

and I tried using a standard genome input:

`
 > export.bw( object = G1, con="/home/bosberg/temp/test.bw", genome="hg19" )
Error in .local(object, con, format, ...) : 
  unused argument (genome = "hg19")
`

And that's pretty much where I'm stuck. It's probably just a silly formatting issue, but it's not at all clear to me what syntax I'm supposed to be using for export.bw

**Comment by Blosberg** [comment]
Addressed this with the latest pull request
