### ISSUE TITLE
pandoc fails

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#39]
Current run (as of posting time) yields:

Error in job diffmeth
pandoc: pigx_bsseq_logo.html: openFile: does not exist (No such file or directory)
Do we need this file? is it supposed to be pulled from some other source?

**Comment by rekado** [comment]
> Error in job diffmeth
> pandoc: pigx_bsseq_logo.html: openFile: does not exist (No such file or directory)
> Do we need this file? is it supposed to be pulled from some other source?

In the Makefile we have a target for this file:

   “report_templates/pigx_bsseq_logo.html”

It is created from “report_templates/pigx_bsseq_logo.html.in” by
replacing the string “#:MAKE” with the base64 encoding of
“images/Logo_PiGx.png”.

If you don’t have this file you probably didn’t run “make”.  Like any
other software package this pipeline needs to be configured and built.
There are four common steps:

0. bootstrap (to generate the scripts for step 1)
1. configure (to specify target paths and detect dependencies)
2. make      (to create all target files)
3. make install (optional, to copy the files to their configured locations)

Step 0 is only performed by developers; users download a bootstrapped
release tarball.
