### ISSUE TITLE
"input file" in report's parameters section is actually an output file

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_bsseq#41]
The generated report has a section entitled "Parameters" containing a table.  In the table there's a row with the name "input file", which is supposed to hold the name of the input file.

However, it holds the name of the file that was the input to the very last step of the pipeline, not the name of the "raw" input file to the pipeline.

This was reported by Bren.

**Comment by alexg9010** [comment]
We should add a complete table of user input files and setting at the beginning of the index.rmd, which is the first part of the final report.

**Comment by rekado** [comment]
This depends on https://github.com/BIMSBbioinfo/pigx_bsseq/issues/60

**Comment by rekado** [comment]
This has been fixed with PR #76
