### ISSUE TITLE
record R package locations at configure time, recover at runtime

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_bsseq#49]
Compute a value for R_LIBS_SITE at configure time and restore it at runtime to ensure that build-time packages are used at runtime.

One way to do this is with `paste(unique(dirname(find.package(pkgs))), sep=':')` for a given vector of package names `pkgs`.   `pkgs` must be a list of *all* R packages including their dependencies.  We don't capture `.libsPath()` because it may include more than what we need.

`pkgs` might be obtained by loading all required first-level dependencies first, and then iterate over all automatically loaded packages.

**Comment by rekado** [comment]
This would get all used library directories for the first level dependencies `pkgs`:

    lapply(pkgs, require, character.only=TRUE)
    paste(unique(dirname(find.package(loadedNamespaces()))), collapse=':')

The result is a string that can be used for R_LIBS_SITE at runtime.  When using Guix the string will consist of many different directories (one for each package), on traditional systems this may only be a single directory.

Either way, this is necessary to ensure that the pipeline uses the same environment at runtime as at configure time (at least by name).

**Comment by rekado** [comment]
Alternatively, we could simply record the R_LIBS_SITE variable if it is set at configure time.  Otherwise we ignore it and assume that all R packages are found in the default locations.  This would be simpler and also correct when environment managers like Guix use R_LIBS_SITE to provide additional packages.

**Comment by Blosberg** [comment]
@rekado ,  I recall you put some plots out on reproducibility recently. Is this issue resolved?

**Comment by rekado** [comment]
This is surprisingly tricky, but I think it may not be all that important after all.

Since the paper focuses on how to do this with Guix, I have implemented capture of the R packages and Python packages in a build phase of the Guix package definitions for all pipelines.  This means that for Guix packages this is already working, but it requires extra work when other package managers (or no package manager at all) are used.

With regard to the scope of the paper I think that's acceptable.

**Comment by Blosberg** [comment]
awesome. Thanks.

**Comment by alexg9010** [comment]
@rekado Is this still required / open ?

**Comment by rekado** [comment]
It's a wishlist issue of dubious value.  Considering the way R works, we can assume that R_LIBS_SITE is sufficient for most purposes.  It isn't fool-proof and it isn't perfect, but it is sufficient.

R_LIBS_SITE will usually point to the root of a directory tree that contains all needed R packages (and their R dependencies).  While it would be super cool if we could forgo the use of R_LIBS_SITE and record the exact location of each and every R package, it wouldn't actually be an improvement in any practical sense.  Any real solution would be a change in R itself; in all other circumstances we either have a single directory tree to work with (so capturing R_LIBS_SITE is sufficient) or we have a package manager that can work around the problem.

I think it's not worth pursuing this issue.

**Comment by alexg9010** [comment]
@rekado Thx!
