### ISSUE TITLE
Change report generation from multi-report-merging to single report generation

### ISSUE THREAD

**Issue by alexg9010** [BIMSBbioinfo/pigx_bsseq#60]
We decided to render the final report only once instead of rendering each part of it separately.
Therefore we want to create the intermediate files first and then pass them during the report rendering. 

- [x] from every report export intermediate objects that are required for final report
- [x] merge contents from single reports into final report
- [x] decide on content of final report (modify/remove sections)
- [ ] decide on wether reports should sample or experiment specific (fastqc-style or multiqc-style)

**Comment by rekado** [comment]
Since #76 has been merged I close this issue.
