### ISSUE TITLE
snakemake commands prepended with ` set -euo pipefail;  `

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#67]
No idea where this string comes fromt or what it means, but I've seen this string showing up at the beginning of snakemake commands a couple times, most recently documented in a testing run here: 
https://github.com/BIMSBbioinfo/pigx_bsseq/issues/42

**Comment by rekado** [comment]
This is not a bug but by design.

Snakemake does this in the executor method of the "shell" class.

**Comment by rekado** [comment]
You can find an explanation of this string in the Bash manual.  Run `info '(bash) The Set Builtin'` to access the relevant section in an info reader.
