### ISSUE TITLE
check write permission of genome reference directory

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/pigx_bsseq#74]
Genome preparation will attempt to write to the genome directory.  Make sure we can write there, otherwise abort.

(Future implementations could write the prepared output elsewhere.)

**Comment by Blosberg** [comment]
>  Make sure we can write there, otherwise abort.

Not necessarily. If the reference genome directory already contains the sub-directory `Bisulfite_Genome`, then we don't need write permissions.

If **either** of the following two things are true:

(1) we have write permission to create our own Bisulfite-converted version of the reference genome,
**or**
(2) the user has already converted the reference genome for us

then SM should carry-one happily. Only if **both** of the above two cases are true, then we should abort.

**Comment by rekado** [comment]
Closed with 66bbb9965b75a0cb066a7ba273a25e319c00d8be.
