### ISSUE TITLE
output documentation to pigx_work

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#75]
the subfolder of output-dir that was previously named `/path-links/` and is now being changed to `/pigx_work/` should contain a text file describing roughly what is going into this folder and how the file links there can be used for traceability to identify the source file of origin, etc.

**Comment by rekado** [comment]
Closed with https://github.com/BIMSBbioinfo/pigx_bsseq/commit/aa85c608c9d78c1c1c977db47f78aa574aff2315
