### ISSUE TITLE
allow non-numeric treatment vectors

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#80]
From slack discussion:

bren:
For the moment, I'm happy with just  telling the user that the treatment label must be numeric as long as we flag a clear error whenever that's not the case, that's good enough for me.

rekado:  
readability is a good reason. as a user I would totally provide a word even, not a letter, not a number. maybe even a bunch of words, aka sentence.

alexgos:
one thing that could work:
```> vec <- c("a","b","b",0,1)
> lookup <- setNames(unique(vec),seq_along(unique(vec)))
> lookup
  1   2   3   4 
"a" "b" "0" "1" 
> match(vec,lookup)
[1] 1 2 2 3 4```

All good points. But for the moment, this is being related to a "wishlist" issue.

**Comment by Blosberg** [comment]
Current plan is to upgrade to version 1.4 of methylkit from bioconductor. According to @al2na , this will allow for this feature.

**Comment by alexg9010** [comment]
fixed with https://github.com/BIMSBbioinfo/pigx_bsseq/pull/159
