### ISSUE TITLE
remove overlap from Extract Methylation Calls figure

### ISSUE THREAD

**Issue by Blosberg** [BIMSBbioinfo/pigx_bsseq#85]
Looks ugly in the report.
![overlap](https://user-images.githubusercontent.com/23317778/35049319-e0f7d68a-fb9f-11e7-9629-8fadeea9356c.png)

Doesn't matter if par(mfrow...
is set back to (1,1)
the overlap is still there, and the title is hard-coded by the `main` value in methylkit: https://github.com/al2na/methylKit/blob/49feeb8f6ba304b784c413db812e9de704a0c4ec/R/backbone.R#L1646

It doesn't actually compromise the readability much, so wishlisted for now.

**Comment by Blosberg** [comment]
It's actually worse than above. Here is a screenshot from a report generated with actual data:

![screen shot 2018-01-23 at 15 16 23](https://user-images.githubusercontent.com/23317778/35280465-a4f64b34-0050-11e8-9693-80d9bf7d7f50.png)

Axis labels and titles are also overlapping; data labels are way more than necessary, (and are overlapping); the title is redundant. For lots of reasons I'd suggest we just stop using `getMethylationStats` (or re-write it.)

**Comment by al2na** [comment]
you can try to play with markdown settings to plot a longer figure
fig.height for example
